### ISSUE TITLE
Peer Review - Code 301 Day 10

### ISSUE THREAD

**Issue by ckperez** [erinroby/portfolio#14]
Redundant Code: No need to initialize Project.all as an empty array on line 10 of project.js now that the array is created on line 23.

SMACSS: CSS files could be split up and put into SMACCS directories. Also, you have a lot of CSS in your base file that might be better in a state.css file.

Your CSS is super clean overall and looks pretty easy to understand and dive into. I'm a big fan of the UI that you've accomplished with your code. Good layout and color scheme! Also, everything is really DRY.

Aaaaand... super awesome use of an api.

**Comment by erinroby** [comment]
Thanks again, Chris!
