### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dmcfly85** [erinroby/portfolio#6]
index.html - line 15, no current need for a clearfix

project.js: function Project, could iterate over object rather than manual pull each element

projectView.js: line 23 is no longer needed with handlebar implementation

CSS: Accomplishing so much style with so little css, great! 

I love your clean and organized your code -- very inspirational.

**Comment by erinroby** [comment]
https://github.com/erinroby/portfolio/pull/7

pull request with issue updates.
